name: Use Secrets in Workflow

on:
  push:
    branches:
      - main

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print a Secret
      env:
        API_KEY: ${{ secrets.API_KEY }}
        Repository: $ {{ github.repository }}
      run: |
        echo "The API key is: $API_KEY"
        echo "Repo is: $Repository"
